Change in design and add links
TobiasSteinhagen/QuizApp pull request #13
Opened 2023-08-08 11:01 UTC by TobiasSteinhagen

Unfortunately it's a bigger pull request.

Please check the following:

- add BEM to my css classes
- cleaned thee css structure a little bit
- add the active class to the icons in my footer
- add the bookmark.html and the links to the home icon and the bookmark icon
- add the fav-icon to the cards in the bookmarks.html

2023-08-08 18:29 UTC, shrocket commented on components/quizcards.css
> +  font-size: 10px;
You're using a lot of px units in general, but this is the first font in px I've found. You might want to consider using rem or em units for fonts and anything else that should change size as the website changes size. You know this already. This is a friendly reminder!

2023-08-08 18:30 UTC, shrocket commented on html/bookmarks.html
> +            <button type="quizcard__answer-button" class="button">Show Answer</button>
Do you maybe want to switch type and class here, so that the class has the BEM naming convention and the button is just a button?

2023-08-08 18:31 UTC, shrocket commented on html/bookmarks.html
> +            <a href="http://127.0.0.1:3000/html/bookmarks.html"><img class="nav__icon nav__icon--active"
is this anchor address (and the one below in line 28) right?

2023-08-08 18:33 UTC, shrocket commented on index.html
>          <section class="quizcard">
This class name (and many others, really; I'm just now noticing) doesn't conform to BEM naming conventions.

2023-08-08 18:34 UTC, shrocket commented on index.html
> +            <a href="http://127.0.0.1:3000/html/bookmarks.html"><img class="nav__icon"
Here's that weird IP address again. Will it resolve properly?

2023-08-08 18:38 UTC, shrocket requested changes
I'd love to have a look at this on vercel, but can't figure out how . . .
Feel free to let me know if you have any questions about my comments!
I'm going to mark "request changes" mostly to see what happens and also because I think that's probably proper workflow!

2023-08-09 13:28 UTC, TobiasSteinhagen commented on html/bookmarks.html
> +            <button type="quizcard__answer-button" class="button">Show Answer</button>
my local html has this change, maybe i already fixed it after the push.

2023-08-09 13:29 UTC, TobiasSteinhagen commented on html/bookmarks.html
> +            <a href="http://127.0.0.1:3000/html/bookmarks.html"><img class="nav__icon nav__icon--active"
works for me localy, didn't deployed bookmark.html yet. I will deploy it, after this pull request.

2023-08-09 13:39 UTC, TobiasSteinhagen commented on html/bookmarks.html
> +            <button type="quizcard__answer-button" class="button">Show Answer</button>
found it in the bookmars.html....and changed it.

2023-08-09 15:18 UTC, shrocket commented on components/global.css
> +*/
mine looks like this: 
`:root {
  --color-scarlet: #d00000;
  --color-cream: #f5f1e7;
  --color-gray: #c7c8ca;
}`

2023-08-09 15:21 UTC, shrocket commented on components/quizcards.css
> +.quizcard__categorie {
In this case, using an almost German word ("categorie") is not a problem, since it's so close to the English, but I think all the code is supposed to be in English, and you may want to find minor things like this and root them out. Category / Categories

😄

2023-08-09 15:22 UTC, shrocket commented on components/header.css
>    color: black;
There are plenty of other places, too, but here's one place where you could replace colors with variables!

2023-08-09 15:23 UTC, shrocket commented on html/bookmarks.html
> +        <p class="header__paragraph">Das Quiz über Dinge,<br> bei denen man nicht wusste,<br> sie wissen zu wollen.</p>
Wouldn't you like to solve your line-braking problems in CSS rather than in HTML?

2023-08-09 15:26 UTC, shrocket requested changes
The only changes I'm actually requesting are those that have to do with color variables. The `<br>` question and the Denglish question I leave entirely to you!

2023-08-09 15:46 UTC, TobiasSteinhagen commented on html/bookmarks.html
> +        <p class="header__paragraph">Das Quiz über Dinge,<br> bei denen man nicht wusste,<br> sie wissen zu wollen.</p>
I wanted to get rid of it anyway :D so I just deleted it, but yeah, I think you are right. Always try to design in css and not html.

2023-08-09 15:52 UTC, TobiasSteinhagen commented on components/global.css
> +*/
That was very helpful, I had a little problem with my code, therefore it didn't worked in another project. I added variables for my color and my icon width and the hover effect.

2023-08-09 15:54 UTC, merged